<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>raccoon_watchdog</name>
  <version>0.0.0</version>
  <description>
    Raccoon Watchdog is a ROS2 package that will monitor the health of the robot and all sensors.
    It will run on both the Jetson and the Raspberry Pi. It will monitor the health of the robot and all sensors, and if any of them fail, it will restart a node.
  </description>
  <maintainer email="reachadamzhang@gmail.com">Adam Zhang</maintainer>
  <license>Apache-2.0</license>

  <exec_depend>rclpy</exec_depend>
  <exec_depend>sensor_msgs</exec_depend>

  <test_depend>ament_copyright</test_depend>
  <test_depend>ament_flake8</test_depend>
  <test_depend>ament_pep257</test_depend>
  <test_depend>python3-pytest</test_depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
